wip typing

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -100,8 +100,9 @@ repos:
       - id: python-match-case-builtins
       # ast-based hooks
       - id: python-check-dunder-all
-        files: '(^src/|^tests/)'
+        files: '^src/'
       - id: python-check-typing
+        args: ["--check-no-return-union"]
         files: '^src/|tests/'
       - id: python-direct-imports
       - id: python-no-mixed-args
@@ -160,10 +161,19 @@ repos:
       exclude: '/tasks/.*'
   # pyright
   - repo: https://github.com/RobertCraigie/pyright-python
-    rev: v1.1.373
+    rev: v1.1.374
     hooks:
       - id: pyright
         # REF: https://stackoverflow.com/a/20401674
-        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
+        entry: |
+          sh -c '\
+            result=$(script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)");
+            count=$(echo "$result" | wc -l);
+            if [ "$count" -ne 0 ]; then \
+              echo "$result"; \
+              echo "\033[1;31mFound ${count} errors\033[0m"; \
+              exit 1; \
+            fi \
+          ' --
         files: (^src/|^tests/)
         exclude: '/tasks/.*'
