updated lazydict

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -167,14 +167,14 @@ repos:
         # REF: https://stackoverflow.com/a/20401674
 #        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
         entry: |
-          sh -c '\
-            result=$(script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)");
-            count=$(echo -n "$result" | wc -l);
-            if [ "$count" -ne 0 ]; then \
-              echo "$result"; \
-              echo "\033[1;31mFound ${count} errors\033[0m"; \
-              exit 1; \
-            fi \
+          sh -c '
+              result=$(script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)");
+              count=$(echo -n "$result" | grep -c "^");
+              if [ "$count" -ne 0 ]; then
+                  echo "$result";
+                  echo "\033[1;31mFound ${count} errors\033[0m";
+                  exit 1;
+              fi
           ' --
         files: (^src/|^tests/)
         exclude: '/tasks/.*'
