updated deps

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -166,6 +166,25 @@ repos:
         entry: '\#\s*\#'
         types: [python]
         files: '^src/|^tests/'
+  # pyright
+  - repo: https://github.com/RobertCraigie/pyright-python
+    rev: v1.1.385
+    hooks:
+      - id: pyright
+        # SEE: https://stackoverflow.com/a/20401674
+        #        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
+        entry: |
+          sh -c '
+              result=$(script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)");
+              count=$(echo -n "$result" | grep -c "^");
+              if [ "$count" -ne 0 ]; then
+                  echo "$result";
+                  echo "\033[1;31mFound ${count} errors\033[0m";
+                  exit 1;
+              fi
+          ' --
+        files: '^src/|^tests/'
+        exclude: '/tasks/'
   # mypy
   - repo: local
     hooks:
@@ -183,22 +202,3 @@ repos:
         - "--hide-error-end"
         - "--no-pretty"
         - "--"
-  # pyright
-  - repo: https://github.com/RobertCraigie/pyright-python
-    rev: v1.1.385
-    hooks:
-      - id: pyright
-        # SEE: https://stackoverflow.com/a/20401674
-#        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
-        entry: |
-          sh -c '
-              result=$(script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)");
-              count=$(echo -n "$result" | grep -c "^");
-              if [ "$count" -ne 0 ]; then
-                  echo "$result";
-                  echo "\033[1;31mFound ${count} errors\033[0m";
-                  exit 1;
-              fi
-          ' --
-        files: '^src/|^tests/'
-        exclude: '/tasks/'
